# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e132f0ffd4972a899fcbfe5ba1afc8697b0f916bd9a9f7a6cb15f710d656cf9bcb448492850c98ecbb1bb48c55cb2ccbd8bc31f3066ce0ae25452a1df5aa46d

test:
  secret_key_base: 6e7dfc52b17096ba476865546b5d704ce5eccf3b1a4ec8812092da20df7512c886038153f837227fe5bf39259ce973690a8f47f948087e7569ff51697582aa63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
